namespace MediPrax.Application.Catalogs;

public record AmdpCategory(string Code, string Name, string Description);

public record AmdpSymptom(
    string CategoryCode,
    string SymptomCode,
    string Name,
    string Description,
    string NarrativeTemplate);

public static class AmdpCatalog
{
    public static IReadOnlyList<AmdpCategory> Categories { get; } = InitCategories();

    public static IReadOnlyList<AmdpSymptom> AllSymptoms { get; } = InitSymptoms();

    public static IReadOnlyList<AmdpSymptom> Search(string term)
    {
        if (string.IsNullOrWhiteSpace(term) || term.Length < 2)
            return [];

        var lower = term.ToLower();
        return AllSymptoms
            .Where(s => s.Name.ToLower().Contains(lower)
                     || s.SymptomCode.ToLower().Contains(lower)
                     || s.CategoryCode.ToLower().Contains(lower)
                     || s.Description.ToLower().Contains(lower))
            .ToList();
    }

    public static IReadOnlyList<AmdpSymptom> GetByCategory(string categoryCode)
    {
        return AllSymptoms
            .Where(s => s.CategoryCode.Equals(categoryCode, StringComparison.OrdinalIgnoreCase))
            .ToList();
    }

    private static List<AmdpCategory> InitCategories() =>
    [
        new("BEW", "Bewusstseinsstörungen", "Störungen der Bewusstseinslage"),
        new("ORI", "Orientierungsstörungen", "Störungen der Orientierung"),
        new("AUF", "Aufmerksamkeits-/Gedächtnisstörungen", "Störungen von Aufmerksamkeit und Gedächtnis"),
        new("FDS", "Formale Denkstörungen", "Störungen des formalen Denkablaufs"),
        new("INH", "Inhaltliche Denkstörungen", "Störungen des Denkinhalts, insbesondere Wahn"),
        new("SIN", "Sinnestäuschungen", "Halluzinationen und Illusionen"),
        new("ICH", "Ich-Störungen", "Störungen des Ich-Erlebens"),
        new("AFF", "Störungen der Affektivität", "Störungen der Stimmung und des Affekts"),
        new("ANT", "Antriebs-/Psychomotorik", "Störungen von Antrieb und Psychomotorik"),
        new("CIR", "Circadiane Besonderheiten", "Tageszeitliche Schwankungen"),
        new("SUI", "Suizidalität", "Suizidale Symptomatik"),
        new("SOM", "Somatische Befunde", "Somatische Begleitsymptome"),
    ];

    private static List<AmdpSymptom> InitSymptoms() =>
    [
        // ========== BEW — Bewusstseinsstörungen ==========
        new("BEW", "BEW-1", "Bewusstseinsverminderung",
            "Herabsetzung der Wachheit (Somnolenz, Sopor, Koma)",
            "{Severity} Bewusstseinsverminderung"),
        new("BEW", "BEW-2", "Bewusstseinstrübung",
            "Qualitative Bewusstseinsstörung mit Verwirrtheit",
            "{Severity} Bewusstseinstrübung"),
        new("BEW", "BEW-3", "Bewusstseinseinengung",
            "Einengung des Bewusstseinsumfangs, Fokussierung auf wenige Themen",
            "{Severity} Bewusstseinseinengung"),
        new("BEW", "BEW-4", "Bewusstseinsverschiebung",
            "Verändertes Bewusstseinserleben, subjektiv gesteigerte Wachheit",
            "{Severity} Bewusstseinsverschiebung"),

        // ========== ORI — Orientierungsstörungen ==========
        new("ORI", "ORI-1", "Zeitlich desorientiert",
            "Zeitliche Orientierungsstörung (Datum, Wochentag, Jahreszeit)",
            "zeitlich {Severity} desorientiert"),
        new("ORI", "ORI-2", "Örtlich desorientiert",
            "Örtliche Orientierungsstörung (Aufenthaltsort)",
            "örtlich {Severity} desorientiert"),
        new("ORI", "ORI-3", "Situativ desorientiert",
            "Situative Orientierungsstörung (Erfassung der aktuellen Situation)",
            "situativ {Severity} desorientiert"),
        new("ORI", "ORI-4", "Zur Person desorientiert",
            "Orientierungsstörung zur eigenen Person (Name, Alter, Biographie)",
            "zur Person {Severity} desorientiert"),

        // ========== AUF — Aufmerksamkeits-/Gedächtnisstörungen ==========
        new("AUF", "AUF-1", "Auffassungsstörung",
            "Verminderung der Fähigkeit, Wahrnehmungen in ihrer Bedeutung zu begreifen",
            "{Severity} Auffassungsstörung"),
        new("AUF", "AUF-2", "Konzentrationsstörung",
            "Verminderte Fähigkeit, die Aufmerksamkeit ausdauernd einer Tätigkeit zuzuwenden",
            "{Severity} Konzentrationsstörung"),
        new("AUF", "AUF-3", "Merkfähigkeitsstörung",
            "Herabsetzung der Fähigkeit, neue Informationen aufzunehmen und kurzfristig zu speichern",
            "{Severity} Merkfähigkeitsstörung"),
        new("AUF", "AUF-4", "Gedächtnisstörung",
            "Herabsetzung der Fähigkeit, früher Gelerntes abzurufen",
            "{Severity} Gedächtnisstörung"),
        new("AUF", "AUF-5", "Konfabulation",
            "Erinnerungslücken werden mit Einfällen gefüllt, die für Erinnerungen gehalten werden",
            "Konfabulationen"),
        new("AUF", "AUF-6", "Paramnesie",
            "Erinnerungsverfälschung oder Trugerinnerung",
            "Paramnesien"),

        // ========== FDS — Formale Denkstörungen ==========
        new("FDS", "FDS-1", "Denkhemmung",
            "Subjektiv vom Patienten erlebte Verlangsamung und Erschwerung des Denkens",
            "{Severity} Denkhemmung"),
        new("FDS", "FDS-2", "Denkverlangsamung",
            "Objektiv erkennbares, verlangsamtes Denken",
            "{Severity} Denkverlangsamung"),
        new("FDS", "FDS-3", "Umständliches Denken",
            "Weitschweifiges Denken mit Verlust des roten Fadens",
            "{Severity} umständliches Denken"),
        new("FDS", "FDS-4", "Eingeengtes Denken",
            "Einschränkung des inhaltlichen Denkumfangs, Verhaftetsein an wenige Themen",
            "{Severity} eingeengtes Denken"),
        new("FDS", "FDS-5", "Perseveration",
            "Haftenbleiben an Worten oder Gedanken",
            "Perseverationen"),
        new("FDS", "FDS-6", "Grübeln",
            "Unablässiges Beschäftigtsein mit meist unangenehmen Themen",
            "{Severity} Grübeln"),
        new("FDS", "FDS-7", "Gedankendrängen",
            "Erlebnis, dass ständig neue Gedanken auftreten und sich aufdrängen",
            "Gedankendrängen"),
        new("FDS", "FDS-8", "Ideenflucht",
            "Beschleunigter Gedankenablauf mit ständig neuen Einfällen",
            "Ideenflucht"),
        new("FDS", "FDS-9", "Vorbeireden",
            "Antworten gehen am Thema der Frage vorbei",
            "Vorbeireden"),
        new("FDS", "FDS-10", "Gesperrt/Gedankenabreißen",
            "Plötzlicher Abbruch eines flüssigen Gedankengangs",
            "Gedankenabreißen"),
        new("FDS", "FDS-11", "Inkohärenz/Zerfahrenheit",
            "Zusammenhangloser Gedankenablauf, nicht nachvollziehbar",
            "{Severity} Zerfahrenheit"),
        new("FDS", "FDS-12", "Neologismen",
            "Wortneubildungen, die nicht verständlich sind",
            "Neologismen"),

        // ========== INH — Inhaltliche Denkstörungen ==========
        new("INH", "INH-1", "Zwangsgedanken",
            "Sich aufdrängende Gedanken, die als unsinnig erlebt werden",
            "Zwangsgedanken"),
        new("INH", "INH-2", "Überwertige Ideen",
            "Affektiv hoch besetzte Überzeugungen, die das Denken dominieren",
            "überwertige Ideen"),
        new("INH", "INH-3", "Wahnstimmung",
            "Unbestimmtes Erleben, dass etwas im Gange ist, was den Patienten betrifft",
            "Wahnstimmung"),
        new("INH", "INH-4", "Wahnwahrnehmung",
            "Reale Wahrnehmung wird wahnhaft umgedeutet",
            "Wahnwahrnehmungen"),
        new("INH", "INH-5", "Wahngedanken",
            "Wahnhafte Überzeugungen ohne Sinneswahrnehmungsbezug",
            "Wahngedanken"),
        new("INH", "INH-6", "Beziehungswahn",
            "Wahnhafte Eigenbeziehung: Vorgänge werden auf die eigene Person bezogen",
            "Beziehungswahn"),
        new("INH", "INH-7", "Beeinträchtigungswahn",
            "Wahnhafte Überzeugung, geschädigt oder benachteiligt zu werden",
            "Beeinträchtigungswahn"),
        new("INH", "INH-8", "Verfolgungswahn",
            "Wahnhafte Überzeugung, verfolgt zu werden",
            "Verfolgungswahn"),
        new("INH", "INH-9", "Eifersuchtswahn",
            "Wahnhafte Überzeugung der Untreue des Partners",
            "Eifersuchtswahn"),
        new("INH", "INH-10", "Schuldwahn",
            "Wahnhafte Überzeugung, sich schuldig gemacht zu haben",
            "Schuldwahn"),
        new("INH", "INH-11", "Verarmungswahn",
            "Wahnhafte Überzeugung, arm zu werden oder zu verarmen",
            "Verarmungswahn"),
        new("INH", "INH-12", "Hypochondrischer Wahn",
            "Wahnhafte Überzeugung, krank zu sein",
            "hypochondrischer Wahn"),
        new("INH", "INH-13", "Größenwahn",
            "Wahnhafte Selbstüberschätzung, besondere Fähigkeiten oder Bedeutung",
            "Größenwahn"),
        new("INH", "INH-14", "Andere Wahninhalte",
            "Sonstige wahnhafte Überzeugungen",
            "sonstige Wahninhalte"),

        // ========== SIN — Sinnestäuschungen ==========
        new("SIN", "SIN-1", "Illusionen",
            "Verfälschte Wahrnehmung realer Sinnesreize",
            "Illusionen"),
        new("SIN", "SIN-2", "Stimmenhören (Phoneme)",
            "Akustische Halluzinationen in Form von Stimmen",
            "Stimmenhören"),
        new("SIN", "SIN-3", "Optische Halluzinationen",
            "Visuelle Halluzinationen ohne realen Reiz",
            "optische Halluzinationen"),
        new("SIN", "SIN-4", "Körperhalluzinationen",
            "Taktile oder zoenästhetische Halluzinationen",
            "Körperhalluzinationen"),
        new("SIN", "SIN-5", "Geruchs-/Geschmackshalluzinationen",
            "Olfaktorische oder gustatorische Halluzinationen",
            "Geruchs-/Geschmackshalluzinationen"),
        new("SIN", "SIN-6", "Pseudohalluzinationen",
            "Halluzinationen, die als nicht real erkannt werden",
            "Pseudohalluzinationen"),

        // ========== ICH — Ich-Störungen ==========
        new("ICH", "ICH-1", "Derealisation",
            "Die Umgebung wird als unwirklich oder fremd erlebt",
            "{Severity} Derealisation"),
        new("ICH", "ICH-2", "Depersonalisation",
            "Das eigene Ich oder der eigene Körper wird als fremd erlebt",
            "{Severity} Depersonalisation"),
        new("ICH", "ICH-3", "Gedankenausbreitung",
            "Erleben, dass eigene Gedanken von anderen mitgedacht werden",
            "Gedankenausbreitung"),
        new("ICH", "ICH-4", "Gedankenentzug",
            "Erleben, dass Gedanken von außen entzogen werden",
            "Gedankenentzug"),
        new("ICH", "ICH-5", "Gedankeneingebung",
            "Erleben, dass Gedanken von außen eingegeben werden",
            "Gedankeneingebung"),
        new("ICH", "ICH-6", "Fremdbeeinflussungserlebnisse",
            "Erleben, von außen gesteuert oder beeinflusst zu werden",
            "Fremdbeeinflussungserlebnisse"),

        // ========== AFF — Störungen der Affektivität ==========
        new("AFF", "AFF-1", "Ratlosigkeit",
            "Erleben von Unsicherheit und Verwunderung über die eigene Situation",
            "Ratlosigkeit"),
        new("AFF", "AFF-2", "Gefühl der Gefühllosigkeit",
            "Klagen über innere Leere und fehlendes Gefühlserleben",
            "Gefühl der Gefühllosigkeit"),
        new("AFF", "AFF-3", "Affektarm",
            "Verminderung der affektiven Ansprechbarkeit und Modulationsfähigkeit",
            "{Severity} affektverarmt"),
        new("AFF", "AFF-4", "Störung der Vitalgefühle",
            "Beeinträchtigung des Körpergrundgefühls und der Leibnähe",
            "Störung der Vitalgefühle"),
        new("AFF", "AFF-5", "Deprimiert/Traurig",
            "Niedergeschlagenheit, Traurigkeit",
            "{Severity} deprimiert"),
        new("AFF", "AFF-6", "Hoffnungslos",
            "Fehlende Zukunftsperspektive, Pessimismus",
            "{Severity} hoffnungslos"),
        new("AFF", "AFF-7", "Ängstlich",
            "Angsterleben ohne konkreten Anlass oder übermäßige Angst",
            "{Severity} ängstlich"),
        new("AFF", "AFF-8", "Euphorisch",
            "Inadäquat gehobene Stimmungslage",
            "{Severity} euphorisch"),
        new("AFF", "AFF-9", "Dysphorisch",
            "Missmutig-gereizte Verstimmung",
            "{Severity} dysphorisch"),
        new("AFF", "AFF-10", "Gereizt",
            "Erhöhte Bereitschaft zu aggressiven Affektdurchbrüchen",
            "{Severity} gereizt"),
        new("AFF", "AFF-11", "Innerlich unruhig",
            "Inneres Getriebensein, Unfähigkeit zur Entspannung",
            "{Severity} innerlich unruhig"),
        new("AFF", "AFF-12", "Klagsam/Jammrig",
            "Ständiges Klagen über Beschwerden",
            "{Severity} klagsam"),
        new("AFF", "AFF-13", "Insuffizienzgefühle",
            "Gefühl, den Anforderungen nicht gewachsen zu sein",
            "Insuffizienzgefühle"),
        new("AFF", "AFF-14", "Gesteigertes Selbstwertgefühl",
            "Überhöhte Einschätzung der eigenen Person",
            "gesteigertes Selbstwertgefühl"),
        new("AFF", "AFF-15", "Schuldgefühle",
            "Übermäßige Selbstvorwürfe, Schulderleben",
            "{Severity} Schuldgefühle"),
        new("AFF", "AFF-16", "Ambivalent",
            "Gleichzeitiges Bestehen gegensätzlicher Gefühle",
            "Ambivalenz"),
        new("AFF", "AFF-17", "Parathymie",
            "Inadäquater Affekt, Gefühlsausdruck passt nicht zum Inhalt",
            "Parathymie"),
        new("AFF", "AFF-18", "Affektlabil",
            "Rasch wechselnde Gefühlslagen",
            "{Severity} affektlabil"),
        new("AFF", "AFF-19", "Affektstarr/Affektinkontinent",
            "Mangelnde affektive Modulationsfähigkeit oder fehlende Affektkontrolle",
            "Affektstarrheit"),

        // ========== ANT — Antriebs-/Psychomotorik ==========
        new("ANT", "ANT-1", "Antriebsarm",
            "Verminderung von Energie und Initiative",
            "{Severity} antriebsgemindert"),
        new("ANT", "ANT-2", "Antriebsgehemmt",
            "Subjektiv erlebte Blockierung des Antriebs",
            "{Severity} antriebsgehemmt"),
        new("ANT", "ANT-3", "Antriebsgesteigert",
            "Vermehrte Energie und gesteigerte Initiative",
            "{Severity} antriebsgesteigert"),
        new("ANT", "ANT-4", "Motorisch unruhig",
            "Gesteigerte, oft ungerichtete motorische Aktivität",
            "{Severity} motorisch unruhig"),
        new("ANT", "ANT-5", "Parakinesen",
            "Qualitativ abnorme Bewegungen (Tics, Stereotypien)",
            "Parakinesen"),
        new("ANT", "ANT-6", "Manierismen",
            "Bizarr anmutende, verschrobene Bewegungen",
            "Manierismen"),
        new("ANT", "ANT-7", "Stupor",
            "Starrezustand des ganzen Körpers bei wachem Bewusstsein",
            "Stupor"),
        new("ANT", "ANT-8", "Mutismus",
            "Wortkargheit bis Nichtsprechen",
            "Mutismus"),
        new("ANT", "ANT-9", "Logorrhoe",
            "Gesteigerter Redefluss, kaum zu unterbrechen",
            "Logorrhoe"),
        new("ANT", "ANT-10", "Sozialer Rückzug",
            "Verminderung sozialer Kontakte und Aktivitäten",
            "{Severity} sozialer Rückzug"),

        // ========== CIR — Circadiane Besonderheiten ==========
        new("CIR", "CIR-1", "Morgentief",
            "Besonders ausgeprägte Symptomatik am Morgen",
            "Morgentief"),
        new("CIR", "CIR-2", "Abendtief",
            "Besonders ausgeprägte Symptomatik am Abend",
            "Abendtief"),

        // ========== SUI — Suizidalität ==========
        new("SUI", "SUI-1", "Lebensmüdigkeit",
            "Äußerung, das Leben habe keinen Sinn",
            "Lebensmüdigkeit"),
        new("SUI", "SUI-2", "Suizidgedanken",
            "Gedanken, sich das Leben zu nehmen",
            "Suizidgedanken"),
        new("SUI", "SUI-3", "Suizidabsichten",
            "Konkrete Absicht zur Selbsttötung",
            "Suizidabsichten"),
        new("SUI", "SUI-4", "Suizidhandlungen",
            "Frühere oder aktuelle suizidale Handlungen",
            "Suizidhandlungen"),

        // ========== SOM — Somatische Befunde ==========
        new("SOM", "SOM-1", "Schlafstörungen",
            "Ein-/Durchschlafstörungen, Früherwachen",
            "Schlafstörungen"),
        new("SOM", "SOM-2", "Appetitminderung",
            "Verminderter Appetit",
            "Appetitminderung"),
        new("SOM", "SOM-3", "Appetitsteigerung",
            "Gesteigerter Appetit",
            "Appetitsteigerung"),
        new("SOM", "SOM-4", "Gewichtsabnahme",
            "Ungewollter Gewichtsverlust",
            "Gewichtsabnahme"),
        new("SOM", "SOM-5", "Gewichtszunahme",
            "Ungewollte Gewichtszunahme",
            "Gewichtszunahme"),
        new("SOM", "SOM-6", "Libidoverlust",
            "Vermindertes sexuelles Verlangen",
            "Libidoverlust"),
        new("SOM", "SOM-7", "Sexuelle Funktionsstörung",
            "Störung der sexuellen Funktion",
            "sexuelle Funktionsstörung"),
        new("SOM", "SOM-8", "Kopfdruck/Kopfschmerzen",
            "Kopfdruckgefühl oder Kopfschmerzen",
            "Kopfdruck/Kopfschmerzen"),
    ];
}
